# Generated by Django 4.2 on 2023-05-18 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("Macho", "Male"), ("Hembra", "Female")], max_length=10
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        choices=[("Sin raza", "No Breed"), ("De raza", "Has Breed")],
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
