# Generated by Django 4.2 on 2023-05-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("Macho", "Male"), ("Hembra", "Female")], max_length=10
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        choices=[("Sin raza", "No Breed"), ("De raza", "Has Breed")],
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.IntegerField(default=1, null=True, verbose_name="Dueño"),
                ),
            ],
        ),
    ]
