# Generated by Django 4.2 on 2023-05-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="breed",
            field=models.CharField(
                choices=[
                    ("Sin raza", "Sin Raza"),
                    ("Coker", "Coker"),
                    ("Pastor aleman", "Pastor Aleman"),
                    ("Bulldog", "Bulldog"),
                    ("Labrador", "Labrador"),
                    ("Golder", "Golden"),
                    ("Caniche", "Caniche"),
                    ("Chihuahua", "Chihuahua"),
                    ("Bulldog Frances", "Bulldog Frances"),
                    ("Beagle", "Beagle"),
                    ("Boxer", "Boxer"),
                    ("Galgo", "Galgo"),
                    ("Dalmata", "Dalmata"),
                    ("Shar pei", "Sharpei"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Blanco", "Blanco"),
                    ("Negro", "Negro"),
                    ("Marrón", "Marron"),
                    ("Blanco y negro", "Blanco Y Negro"),
                    ("Otro color", "Otro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="sex",
            field=models.CharField(
                choices=[("Macho", "Macho"), ("Hembra", "Hembra")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="Attention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Radiografia", "Radiografia"),
                            ("Primeros auxilios", "Primeros Auxilios"),
                            ("Operacion", "Operacion"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dogs.dog",
                    ),
                ),
            ],
        ),
    ]
