# Generated by Django 4.2 on 2023-05-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccination",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Antirrabica", "Antirrabica"),
                    ("Antimoquillo", "Antimoquillo"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
