# Generated by Django 4.2 on 2023-05-30 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vaccination",
            old_name="dosis_number",
            new_name="applied_dose",
        ),
        migrations.RemoveField(
            model_name="vaccination",
            name="total_dosis",
        ),
    ]
