# Generated by Django 4.2.1 on 2023-05-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='type',
            field=models.CharField(blank=True, choices=[('Radiografia', 'Radiografia'), ('Primeros auxilios', 'Primeros Auxilios'), ('Operacion', 'Operacion'), ('Otros Servicios', 'Otros Servicios')], max_length=20, null=True),
        ),
    ]
