# Generated by Django 4.2 on 2023-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0002_rename_dosis_number_vaccination_applied_dose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccination",
            name="applied_dose",
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
