# Generated by Django 4.2.1 on 2023-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('Sin raza', 'Sin Raza'), ('Coker', 'Coker'), ('Pastor aleman', 'Pastor Aleman'), ('Bulldog', 'Bulldog'), ('Labrador', 'Labrador'), ('Golder', 'Golden'), ('Caniche', 'Caniche'), ('Chihuahua', 'Chihuahua'), ('Bulldog Frances', 'Bulldog Frances'), ('Beagle', 'Beagle'), ('Boxer', 'Boxer'), ('Galgo', 'Galgo'), ('Dalmata', 'Dalmata'), ('Shar pei', 'Sharpei')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, choices=[('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Marrón', 'Marron'), ('Blanco y negro', 'Blanco Y Negro'), ('Otro color', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
    ]
