# Generated by Django 4.2 on 2023-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0002_alter_vaccination_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attention",
            name="date_of_attention",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attention",
            name="description",
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
