# Generated by Django 4.2.1 on 2023-05-21 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_breed_alter_dog_color_alter_dog_sex'),
        ('dogs', '0003_rename_descripcion_attention_description_and_more'),
    ]

    operations = [
    ]
