# Generated by Django 4.2 on 2023-05-24 19:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0003_attention_date_of_attention_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attention",
            name="date_of_attention",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date.today,
                        message="La fecha de atención debe ser anterior a la fecha de hoy",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="attention",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=120,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        120, message="La descripción es muy larga"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=120,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        120, message="La descripción es muy larga"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="name",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        15, message="El nombre es muy largo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="brand",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        20, message="El nombre de la marca es muy largo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="date_of_application",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date.today,
                        message="La fecha de atención debe ser anterior a la fecha de hoy",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="lot",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        14, message="El nombre del lote es muy largo"
                    )
                ],
            ),
        ),
    ]
