# Generated by Django 4.2 on 2023-05-24 19:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0004_alter_attention_date_of_attention_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="date_of_birth",
            field=models.DateField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date.today,
                        "La fecha de nacimiento del perro debe ser anterior a hoy",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=120,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        120,
                        message="La descripción debe tener a lo sumo 120 caracteres",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="name",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        15, message="El nombre debe tener como máximo 15 letras"
                    )
                ],
            ),
        ),
    ]
