# Generated by Django 4.2 on 2023-05-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0004_alter_vaccination_applied_dose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Grande", "Grande"),
                    ("Mediano", "Mediano"),
                    ("pequeño", "Pequeño"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
