# Generated by Django 4.2 on 2023-05-24 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0005_alter_dog_date_of_birth_alter_dog_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attention",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=120,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        120,
                        message="La descripción debe tener a lo sumo 120 caracteres",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="description",
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="brand",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        20,
                        message="El nombre de la marca no puede superar los 20 caracteres",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="lot",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        14,
                        message="El nombre del lote no puede superar los 15 caracteres",
                    )
                ],
            ),
        ),
    ]
