# Generated by Django 4.2 on 2023-06-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0005_alter_dog_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="suggestions",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
