# Generated by Django 4.2 on 2023-05-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dogs", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dogs",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="dogs.dog"
            ),
        ),
    ]
