# Generated by Django 4.2 on 2023-07-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_discount",
            field=models.BooleanField(default=False),
        ),
    ]
