# Generated by Django 4.2.1 on 2023-05-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Shift',
        ),
    ]
