# Generated by Django 4.2 on 2023-06-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="media/")),
                ("campaign_name", models.CharField(max_length=30)),
                (
                    "description",
                    models.TextField(blank=True, max_length=120, null=True),
                ),
                ("target_date", models.DateTimeField(blank=True)),
                ("target_money", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "actual_money",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
