# Generated by Django 4.2 on 2023-06-17 17:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="target_date",
            field=models.DateField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date.today,
                        message="La fecha objetivo debe ser posterior a la fecha de hoy",
                    )
                ],
            ),
        ),
    ]
