# Generated by Django 4.2.1 on 2023-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dog',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
