# Generated by Django 4.2.1 on 2023-05-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_appointment_mandado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mandado',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
