# Generated by Django 4.2.1 on 2023-05-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shift_state_alter_shift_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='user',
        ),
    ]
