# Generated by Django 4.2.1 on 2023-07-02 19:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(20, message='El nombre de la veterinaria no puede superar los 20 caracteres')])),
                ('address', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MaxLengthValidator(14, message='La direccion no puede superar los 15 caracteres')])),
                ('date_of_guards', models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date.today, message='La fecha de guardia no debe ser anterior a la fecha de hoy')])),
            ],
        ),
    ]
