# Generated by Django 4.2 on 2023-07-08 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guards",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        14, message="La direccion no puede superar los 15 caracteres"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="guards",
            name="vet",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        20,
                        message="El nombre de la veterinaria no puede superar los 20 caracteres",
                    )
                ],
            ),
        ),
    ]
