# Generated by Django 4.2 on 2023-06-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perdidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostpost",
            name="image",
            field=models.ImageField(null=True, upload_to="perros"),
        ),
    ]
