# Generated by Django 4.2 on 2023-06-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perdidos", "0002_lostpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostpost",
            name="image",
            field=models.ImageField(null=True, upload_to="media/"),
        ),
    ]
