# Generated by Django 4.2.1 on 2023-06-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdidos', '0003_lostpost_publication_date'),
        ('perdidos', '0004_lostpost_publication_date'),
    ]

    operations = [
    ]
